/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.itson.diseñosoftware.farmaciagi.interfaces;

import com.mycompany.farmaciagi_subsistema_compra.GestorCompraProductos;
import com.mycompany.farmaciagi_subsistema_compra.IGestorCompraProductos;
import com.mycompany.farmaciagi_subsistema_compra_excepciones.GestorCompraProductosException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.itson.disenosoftware.farmaciagi_dtos.ProductoDTO;
import org.itson.disenosoftware.farmaciagi_dtos.ProveedorDTO;
import org.itson.disenosoftware.farmaciagi_subsistema_proveedores.GestorProveedores;
import org.itson.disenosoftware.farmaciagi_subsistema_proveedores.IGestorProveedores;

/**
 *
 * @author Enrique Rodriguez
 */
public class DlgOpcionesProveedores extends javax.swing.JDialog {

    private IGestorProveedores gestorProveedores;
    private List<ProveedorDTO> proveedores;
    private IGestorCompraProductos gestorCompras;
    private ProductoDTO productoSeleccionado;
    public DlgOpcionesProveedores(ProductoDTO productoSeleccionado) {
        initComponents();
        this.productoSeleccionado = productoSeleccionado;
        this.gestorProveedores = new GestorProveedores();
        this.gestorCompras = new GestorCompraProductos();
        this.proveedores = new LinkedList<>();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(216, 215, 255));

        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProveedores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Métodos
    public void llenarTabla(){
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            
            modelo.addColumn("NOMBRE");
            modelo.addColumn("DIRECCION");
            modelo.addColumn("CONTACTO");
            modelo.addColumn("RFC");
            
            proveedores = gestorCompras.encontrarProveedores(productoSeleccionado);
            
            if (!proveedores.isEmpty()) {
                for (ProveedorDTO proveedor : proveedores) {
                    
                    List<String> telefonosExistentes = proveedor.getTelefonos();
                    StringBuilder telefonos = new StringBuilder();
                    for (String telefonosExistente : telefonosExistentes) {
                        telefonos.append(telefonosExistente).append(",");
                    }
                    if (telefonos.length() > 0) {
                        telefonos.delete(telefonos.length() - 1, telefonos.length());
                    }
                    
                    Object[] fila = {
                        proveedor.getNombre(),
                        proveedor.getDireccion().getCalle()+","+ //TODO: Pensar si esto va de esta forma
                            proveedor.getDireccion().getColonia()+","+
                            proveedor.getDireccion().getNumero()+","+
                            proveedor.getDireccion().getCodigo_postal()+","+
                            proveedor.getDireccion().getCiudad(),
                        telefonos.toString(),
                        proveedor.getRfc()
                    };
                    modelo.addRow(fila);
                }
            }
            
            tblProveedores.setModel(modelo);
            TableColumnModel columnModel = tblProveedores.getColumnModel();
        } catch (GestorCompraProductosException ex) {
            Logger.getLogger(DlgOpcionesProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProveedores;
    // End of variables declaration//GEN-END:variables
}
